#These are parameters for different site subsets of the RBP
contact_sites: [216, 218, 238, 239, 240, 241, 242, 305, 388, 389, 401, 402, 458, 488, 489, 490, 491, 492, 501, 504, 505, 506, 507, 530, 531, 532, 533, 554, 555, 556, 557, 558, 559, 579, 580, 581, 583, 588]
hydrophobic: [401, 402, 531, 532, 557, 558, 559, 305, 579, 580, 581, 458, 588, 488, 489, 490, 240, 504, 505, 506, 507]
salt_bridges: [242,501,533]
h_bond_total: [239,240,241,242,388,389,402,490,491,492,501,506,530,532,533,555,557,559,581]
h_bond_EFNB3: [242,388,389,491,492,501,506,530,532,533,555,557,559,581]
glycans: [159, 306, 378, 417, 481, 529]


### Functional selection filtering parameters
func_times_seen_cutoff: 2
func_std_cutoff: 1

### Binding filtering parameters
min_times_seen_binding: 2.25
max_binding_std: 2
min_func_effect_for_binding: -1.5

### Antibody escape filtering parameters
min_times_seen_ab: 2.25
max_ab_std: 3
frac_models: 0.75
sum_quantile: 0.98
max_quantile: 0.98
min_escape_cutoff: 0.25
min_func_effect_for_ab: -2

### Heatmap parameters
effect_color: 'redblue'
entropy_color: 'greens'
strokewidth_size: 0.25 #strokesize around boxes
background_color: "#d1d3d4" #color for cells without observations

### General Figure properties
width: 200
height: 200

neut_curve_width: 300
neut_curve_height: 200

bubble_width: 300
bubble_height: 250

large_line_width: 800
large_line_height: 100

#.properties(width=config['width'],height=config['height'])